[phases.setup]
nixPkgs = ["nodejs-20_x"]
aptPkgs = ["openssl", "libssl1.1"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate --generator client", "npm run build"]

[start]
cmd = "npx prisma db push --accept-data-loss && node dist/index.js"
